	.file "test.pas"
###########################
#    Generated by PasC    #
###########################

.section	.text
	.globl	main
	.type	main,@function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$17, %esp
	movl	$1, %eax
	movl	%ebp, %edx
	movl	%eax, -4(%edx)
	movl	$2, %eax
	movl	%ebp, %edx
	movl	%eax, -8(%edx)
	movl	%ebp, %edx
	movl	-4(%edx), %eax
	movl	%ebp, %edx
	movl	-8(%edx), %ebx
	cmpl	%ebx, %eax
	setl	%al
	movzbl	%al, %edi
	movl	%ebp, %edx
	movl	%edi, -9(%edx)
	movl	%ebp, %edx
	movb	-9(%edx), %al
	movzbl	%al, %eax
	pushl	%eax
	subl	$4, %esp
	call	_writeln_int
	movl	%ebp, %edx
	movl	-8(%edx), %eax
	movl	%ebp, %edx
	movl	-4(%edx), %ebx
	cmpl	%ebx, %eax
	setl	%al
	movzbl	%al, %edi
	movl	%ebp, %edx
	movl	%edi, -9(%edx)
	movl	%ebp, %edx
	movb	-9(%edx), %al
	movzbl	%al, %eax
	pushl	%eax
	subl	$4, %esp
	call	_writeln_int
	movl	%ebp, %edx
	movl	-4(%edx), %eax
	movl	%ebp, %edx
	movl	-8(%edx), %ebx
	cmpl	%ebx, %eax
	sete	%al
	movzbl	%al, %edi
	movl	%ebp, %edx
	movl	%edi, -9(%edx)
	movl	%ebp, %edx
	movb	-9(%edx), %al
	movzbl	%al, %eax
	pushl	%eax
	subl	$4, %esp
	call	_writeln_int
	movl	%ebp, %edx
	movl	-8(%edx), %eax
	movl	%ebp, %edx
	movl	-4(%edx), %ebx
	cmpl	%ebx, %eax
	setl	%al
	movzbl	%al, %edi
	movl	$0, %eax
	cmpl	%edi, %eax
	sete	%al
	movzbl	%al, %edi
	movl	%ebp, %edx
	movl	%edi, -9(%edx)
	movl	%ebp, %edx
	movb	-9(%edx), %al
	movzbl	%al, %eax
	pushl	%eax
	subl	$4, %esp
	call	_writeln_int
	movl	$1080033280, %eax
	movl	%ebp, %edx
	movl	%eax, -13(%edx)
	movl	%ebp, %edx
	movl	-13(%edx), %eax
	pushl	%eax
	subl	$4, %esp
	call	_writeln_int
	leave
	ret
.LFE0:
	.size	main, .-main

.section	.rodata
.ident	"PasC v1.0"
.section	.node.GNU-stack,"",@progbits
