	.file "test/calcu_real.pas"
###########################
#    Generated by PasC    #
###########################

.section	.text
	.globl	main
	.type	main,@function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$12, %esp
	movl	$1066192077, %eax
	movl	%ebp, %edx
	movl	%eax, -4(%edx)
	movl	$1067030938, %eax
	movl	%ebp, %edx
	movl	%eax, -8(%edx)
	movl	%ebp, %edx
	movl	-4(%edx), %eax
	pushl	%eax
	movl	%ebp, %edx
	movl	-8(%edx), %eax
	pushl	%eax
	flds	4(%esp)
	fadds	(%esp)
	fstps	(%esp)
	movl	(%esp), %edi
	movl	%ebp, %edx
	movl	%edi, -12(%edx)
	movl	%ebp, %edx
	movl	-4(%edx), %eax
	pushl	%eax
	movl	%ebp, %edx
	movl	-8(%edx), %eax
	pushl	%eax
	flds	4(%esp)
	fsubs	(%esp)
	fstps	(%esp)
	movl	(%esp), %edi
	movl	%ebp, %edx
	movl	%edi, -12(%edx)
	movl	%ebp, %edx
	movl	-4(%edx), %eax
	pushl	%eax
	movl	%ebp, %edx
	movl	-8(%edx), %eax
	pushl	%eax
	flds	4(%esp)
	fmuls	(%esp)
	fstps	(%esp)
	movl	(%esp), %edi
	movl	%ebp, %edx
	movl	%edi, -12(%edx)
	movl	%ebp, %edx
	movl	-4(%edx), %eax
	pushl	%eax
	movl	%ebp, %edx
	movl	-8(%edx), %eax
	pushl	%eax
	flds	4(%esp)
	fdivs	(%esp)
	fstps	(%esp)
	movl	(%esp), %edi
	movl	%ebp, %edx
	movl	%edi, -12(%edx)
	leave
	ret
.LFE0:
	.size	main, .-main

.section	.rodata
.ident	"PasC v1.0"
.section	.node.GNU-stack,"",@progbits
