	.file "test.pas"
###########################
#    Generated by PasC    #
###########################

.section	.text
	.globl	main
	.type	main,@function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$13, %esp
	movl	$5, %eax
	pushl	%eax
	movl	$6, %esi
	imull	(%esp), %esi
	subl	$4, %esp
	movl	$3, %edi
	addl	%esi, %edi
	movl	$1, %eax
	subl	%eax, %edi
	movl	%ebp, %edx
	movl	%edi, -4(%edx)
	movl	$1065353216, %eax
	pushl	%eax
	movl	%ebp, %edx
	movl	-4(%edx), %eax
	pushl	%eax
	fildl	(%esp)
	fadds	4(%esp)
	fstps	(%esp)
	movl	(%esp), %edi
	movl	%ebp, %edx
	movl	%edi, -8(%edx)
	movl	$1110423634, %eax
	movl	%ebp, %edx
	movl	%eax, -12(%edx)
	movl	%ebp, %edx
	movl	-8(%edx), %eax
	pushl	%eax
	movl	%ebp, %edx
	movl	-12(%edx), %eax
	pushl	%eax
	flds	0(%esp)
	flds	4(%esp)
	fxch	%st(1)
	fucomip	%st(1), %st
	fstp	%st(0)
	seta	%al
	movzbl	%al, %edi
	addl	$8, %esp
	movl	%ebp, %edx
	movl	%edi, -13(%edx)
	leave
	ret
.LFE0:
	.size	main, .-main

	.globl	 _$FUNC$max
	.type	 _$FUNC$max,@function
_$FUNC$max:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$8, %esp
	movl	$2, %eax
	movl	%ebp, %edx
	movl	%eax, -4(%edx)
	movl	%ebp, %edx
	movl	-4(%edx), %eax
	pushl	%eax
	movl	$1080033280, %eax
	pushl	%eax
	fildl	4(%esp)
	fmuls	(%esp)
	fstps	(%esp)
	movl	(%esp), %edi
	movl	%ebp, %edx
	movl	%edi, -13(%edx)
	leave
	ret
.LFE1:
	.size	_$FUNC$max, .-_$FUNC$max

.section	.rodata
.ident	"PasC v1.0"
.section	.node.GNU-stack,"",@progbits
