	.file "test.pas"
###########################
#    Generated by PasC    #
###########################

.section	.text
	.globl	main
	.type	main,@function
main:
	pushl %ebp
	movl %esp, %ebp
	subl $13, %esp
	movl	$6, %edx
	pushl	%edx
	movl	$5, %edx
	pushl	%edx
	popl	%eax
	imull	(%esp), %eax
	movl	%eax, (%esp)
	popl	%esi
	movl	$3, %edx
	pushl	%edx
	pushl	%esi
	popl	%edi
	popl	%esi
	addl	%edi, %esi
	pushl	%esi
	popl	%edi
	pushl	%edi
	movl	$1, %edx
	pushl	%edx
	popl	%edi
	popl	%esi
	subl	%edi, %esi
	pushl	%esi
	popl	%edi
	pushl	%edi
	movl	%ebp, %eax
	popl	%edx
	movl	%edx, -4(%eax)
	movl	$1065353216, %edx
	pushl	%edx
	movl	%ebp, %eax
	movl	-4(%eax), %edx
	pushl	%edx
	popl	%edi
	popl	%esi
	addl	%edi, %esi
	pushl	%esi
	popl	%edi
	pushl	%edi
	movl	%ebp, %eax
	popl	%edx
	movl	%edx, -8(%eax)
	movl	$1110423634, %edx
	pushl	%edx
	movl	%ebp, %eax
	popl	%edx
	movl	%edx, -12(%eax)
	movl	%ebp, %eax
	movl	-8(%eax), %edx
	pushl	%edx
	movl	%ebp, %eax
	movl	-12(%eax), %edx
	pushl	%edx
	flds	0(%esp)
	flds	4(%esp)
	fxch	%st(1)
	fucomip	%st(1), %st
	fstp	%st(0)
	setl	%al
	movzbl	%al, %eax
	popl	%edi
	popl	%esi
	pushl	%eax
	popl	%edi
	pushl	%edi
	movl	%ebp, %eax
	popl	%edx
	movb	%dl, -13(%eax)
.LFE0:
	.size	main, .-main

	.globl	 _$FUNC$max
	.type	 _$FUNC$max,@function
_$FUNC$max:
	pushl %ebp
	movl %esp, %ebp
	subl $8, %esp
	movl	$2, %edx
	pushl	%edx
	movl	%ebp, %eax
	popl	%edx
	movl	%edx, -4(%eax)
	movl	%ebp, %eax
	movl	-4(%eax), %edx
	pushl	%edx
	movl	$1080033280, %edx
	pushl	%edx
	popl	%edi
	popl	%esi
	mull	%edi, %esi
	pushl	%esi
	popl	%edi
	pushl	%edi
	movl	%ebp, %eax
	popl	%edx
	movl	%edx, -13(%eax)
	leave
	ret
.LFE1:
	.size	_$FUNC$max, .-_$FUNC$max

.section	.rodata
.ident	"PasC v1.0"
.section	.node.GNU-stack,"",@progbits
