	.file "test.pas"
###########################
#    Generated by PasC    #
###########################

.section	.text
	.globl	main
	.type	main,@function
main:
	pushl	%ebp
	movl	%esp, %ebp
	subl	$264, %esp
	leal	_$CONST$_L0, %eax
	movl	%eax, %edi
	movl	%ebp, %edx
	movl	-264(%edx), %eax
	pushl	%eax
	subl	$4, %esp
	call	_writeln_int
	addl	$8, %esp
	leal	_$CONST$_L1, %eax
	movl	%eax, %edi
	pushl	%edi
	subl	$4, %esp
	addl	$1, 4(%esp)
	call	_write_string
	addl	$8, %esp
	movl	%ebp, %edx
	leal	-8(%edx), %eax
	pushl	%eax
	subl	$4, %esp
	call	_read_int
	addl	$8, %esp
	movl	$1, %eax
	movl	%ebp, %edx
	movl	%eax, -4(%edx)
_$JMP$_L0:
	movl	$10, %eax
	movl	%ebp, %edx
	movl	-4(%edx), %ebx
	cmpl	%ebx, %eax
	setl	%al
	movzbl	%al, %edi
	movl	$0, %eax
	cmpl	%edi, %eax
	sete	%al
	movzbl	%al, %edi
	cmpl	$0, %edi
	je	_$JMP$_L1
	movl	$1, %eax
	movl	%ebp, %edx
	movl	-8(%edx), %edi
	addl	%eax, %edi
	movl	%ebp, %edx
	movl	%edi, -8(%edx)
	movl	$1, %eax
	movl	%ebp, %edx
	movl	-4(%edx), %ecx
	addl	%eax, %ecx
	movl	%ebp, %edx
	movl	%ecx, -4(%edx)
	jmp	_$JMP$_L0
_$JMP$_L1:
	movl	%ebp, %edx
	movl	-8(%edx), %eax
	pushl	%eax
	subl	$4, %esp
	call	_writeln_int
	addl	$8, %esp
	leave
	ret
.LFE0:
	.size	main, .-main

.section	.rodata
_$CONST$_L0:
	.string "\015Hello, world!\000"

_$CONST$_L1:
	.string "\018please input r: \000"

.ident	"PasC v1.0"
.section	.node.GNU-stack,"",@progbits
